name: Cypress Tests

on: pull_request

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Testing e2e
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5.5.1
        with:
          start: npm start
